name: APK DJ PRO V3 ULIMATE - PWABuilder
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build APK dari PWA
        uses: pwa-builder/pwa-studio-action@v2
        with:
          url: https://edit-dj.vercel.app
          platform: android
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DJ-PRO-V3-ULIMATE-APK
          path: output/*.apk
