name: APK DJ PRO V3 - FIX JDK NANYA BANGET
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK  
        uses: android-actions/setup-android@v3
        
      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli
        
      - name: Kasih Tau Bubblewrap Lokasi JDK + SDK
        run: |
          mkdir -p ~/.bubblewrap
          echo '{"jdkPath":"'$JAVA_HOME'","androidSdkPath":"'$ANDROID_SDK_ROOT'"}' > ~/.bubblewrap/config.json
          echo "Isi config.json:"
          cat ~/.bubblewrap/config.json
          
      - name: Build APK Non-Interactive
        run: |
          bubblewrap init --manifest=https://edit-dj.vercel.app/manifest.json --directory=twa
          cd twa
          bubblewrap build --skipSigning
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DJ-PRO-V3-ULIMATE-APK
          path: twa/app-release-unsigned.apk
